# compose.yaml
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   
    image: passengers-svc:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: "8080"
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: unless-stopped
