spring: 
  config: 
    import: optional:file:.env[.properties] 

  datasource: 
    url: ${DB_URL:} 
    username: ${DB_USER:} 
    password: ${DB_PASSWORD:} 

  jpa: 
    hibernate: 
      ddl-auto: ${HIBERNATE_DDL_AUTO:none} 
      properties: 
        hibernate: 
          format_sql: ${HIBERNATE_FORMAT_SQL:true} 

  jackson: 
    time-zone: ${APP_TIMEZONE:America/Bogota}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:passenger-events-group}
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

app:

  kafka:
    passenger-topic: ${PASSENGER_TOPIC:sniffer-t3-passengers}
    consumer-enabled: ${KAFKA_CONSUMER_ENABLED:false}
  
  excluded-ids: ${APP_EXCLUDED_IDS:COOCHOFAL250,EMBUSA99}
  passenger-count-tolerance: ${APP_PASSENGER_COUNT_TOLERANCE:200}
  time-threshold-minutes: ${APP_TIME_THRESHOLD_MINUTES:45}
  timezone: ${APP_TIMEZONE:America/Bogota}

  async:
    core-pool-size: ${APP_ASYNC_CORE_POOL_SIZE:2}
    max-pool-size: ${APP_ASYNC_MAX_POOL_SIZE:2}
    queue-capacity: ${APP_ASYNC_QUEUE_CAPACITY:500}